name: Build and Distribute iOS App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-ios:
    name: Build iOS
    runs-on: macos-14  # This specifies an Intel-based runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.15' # Ensuring Node version is as required

    - name: Install Watchman
      run: brew install watchman

    - name: Configure Git
      run: |
        git config --global user.email "stuwashere@gmail.com"
        git config --global user.name "Stuart Morris"

    - name: Install specific Cocoapods version
      run: |
        sudo gem uninstall cocoapods
        sudo gem install cocoapods -v 1.14.3

    - name: Install npm dependencies
      run: npm install
    
    - name: Build iOS App
      env:
        FASTLANE_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        # APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
        # APPLE_DEVELOPER_TEAM_ID: ${{ secrets.APPLE_DEVELOPER_TEAM_ID }}
        # Ensure all necessary environment variables are correctly set
      run: npm run build:ios

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: iOS App IPA
        path: ./TCG_Chat.ipa  # Ensure this is the correct path to the IPA file
