name: Build and Distribute iOS App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-ios:
    name: Build iOS
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.10.0' # Ensuring Node version is as required
        npm-version: '9.0.0'    # Ensuring npm version is as required

    - name: Install npm dependencies
      run: npm install

    - name: Build iOS App
      env:
        FASTLANE_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        # APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
        # APPLE_DEVELOPER_TEAM_ID: ${{ secrets.APPLE_DEVELOPER_TEAM_ID }}
        # Ensure all necessary environment variables are correctly set
      run: npm run build:ios

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: iOS App IPA
        path: ./TCG_Chat.ipa  # Ensure this is the correct path to the IPA file
